### ISSUE TITLE
Variable "callback" is uninitalized in "notify intersection observers"

### ISSUE THREAD

**Issue by foolip** [w3c/IntersectionObserver#113]
http://rawgit.com/WICG/IntersectionObserver/master/index.html#notify-intersection-observers

It should come from the `[[callback]]` slot. (Discovered while trying to find where that slot ended up used.)

**Comment by slightlyoff** [comment]
Great find.

**Comment by miketaylr** [comment]
It looks like this was fixed at some point (step 3.4 of https://w3c.github.io/IntersectionObserver/#notify-intersection-observers-algo)

<img width="842" alt="Screenshot of algorithm, where 3.4 states Let callback be the value of observer’s internal callback slot." src="https://user-images.githubusercontent.com/67283/173297768-0b8264b5-a87f-4571-b412-7da9e568adc6.png">
