### ISSUE TITLE
Conflicting licenses

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IntersectionObserver#141]
There appear to be 3 licenses: 
1. one in the spec (C0)
2. an Apache one [LICENSE](https://github.com/WICG/IntersectionObserver/blob/gh-pages/LICENSE)
3. [LICENSE.md](https://github.com/WICG/IntersectionObserver/blob/gh-pages/LICENSE.md) 

In the WICG, we use should use the [LICENSE.md](https://github.com/WICG/IntersectionObserver/blob/gh-pages/LICENSE.md) one, including in the spec.

**Comment by marcoscaceres** [comment]
Fixed links above.

**Comment by philipwalton** [comment]
Does this apply to #135 as well?

**Comment by marcoscaceres** [comment]
LOL, yes :) So many licenses!

**Comment by ebinnion** [comment]
Hello 👋

To clarify, what license is the polyfill under? And if it's licensed under the w3c license, is it possible to update the license that ships with that file? I'm glad to submit a PR for that.

We were wanting to use this to add better image loading for WordPress sites, but Apache 2.0 is not compatible with GPLv2.

**Comment by marcoscaceres** [comment]
sent a couple of PRs to close this.

**Comment by ebinnion** [comment]
Thank you @marcoscaceres and @philipwalton 🙇
