### ISSUE TITLE
Performance benchmarks of polyfill

### ISSUE THREAD

**Issue by pastelsky** [w3c/IntersectionObserver#144]
Implementation looks very interesting, especially the use of `MutationObserver`. I was wondering how performant is the polyfill when MutationObserver is used, or dirty polling is used.

The existing best practice for lazy loading of images includes attaching a single debounced window scroll listener and using `getBoundingClientRect` check if images are in viewport, but is far from a full proof solution.

One may assume that since IntersectionObserver's are cheap, they could be added to observe each image (and disconnected after images are loaded / load failed). In this case, a person using this polyfill (or any other for that matter) would unknowingly attach a multiple scroll listeners which would harm performance rather than improve it.

It would be interesting to if the performance impact in such a case was explained (or warned about)

**Comment by jimmywarting** [comment]
I'm too also curios about how I can debounce this awesome IntersectionObserver.

I know that the page is gona be 10k pixels high so I insert placeholder elements. When pressing `end`, `scroll into view` or some anchor link that goes to the bottom with an animation. It will scroll pass all elements those making an ajax call to fetch the content for each placeholder.

**Comment by philipwalton** [comment]
> One may assume that since IntersectionObserver's are cheap, they could be added to observe each image (and disconnected after images are loaded / load failed).

I wouldn't exactly say they're "cheap". In this case you wouldn't want a new IntersectionObserver instance per image, you'd just want a single instance that observes multiple images.

> In this case, a person using this polyfill (or any other for that matter) would unknowingly attach a multiple scroll listeners which would harm performance rather than improve it.

Yes, but this would also be a bad use of the native implementation as well. Proper use of the native implementation corresponds with polyfill best practices here. Each IntersectionObserver instance in the polyfill will add a single event listener for each type (scroll, resize, etc.).

But all that being said, the polyfill tries to handle all possible cases, so it's inevitably going to perform worse that a custom-built solution for your particular use case.

**Comment by philipwalton** [comment]
I'm going to close this as I don't have the time to put together benchmarks for this, but I'd be happy to link to them if someone else is able to do so.
