### ISSUE TITLE
Point 8 in section 3.2.5 is wrong

### ISSUE THREAD

**Issue by tobytailor** [w3c/IntersectionObserver#156]
"Otherwise, let threshold be the index of the first entry in observer.thresholds whose value is greater than intersectionRatio." should be "Otherwise, let threshold be the index of the last entry in observer.thresholds whose value is smaller than intersectionRatio."

**Comment by ziyunfei** [comment]
No, it should be "let threshold be the index of the last entry in observer.thresholds whose value is smaller or equal than intersectionRatio; let threshold = threshold + 1"

**Comment by tobytailor** [comment]
Even better :)

**Comment by szager-chromium** [comment]
Good point, thanks.
