### ISSUE TITLE
Clarify zero-pixel intersection behavior

### ISSUE THREAD

**Issue by mstange** [w3c/IntersectionObserver#159]
I'm confused by this test:

``` js
    it('handles targets on the boundary of root', function(done) {

      var spy = sinon.spy();
      io = new IntersectionObserver(spy, {root: rootEl});

      runSequence([
        function(done) {
          targetEl1.style.top = '0px';
          targetEl1.style.left = '-21px';
          targetEl2.style.top = '-20px';
          targetEl2.style.left = '0px';
          io.observe(targetEl1);
          io.observe(targetEl2);
          setTimeout(function() {
            expect(spy.callCount).to.be(1);
            var records = sortRecords(spy.lastCall.args[0]);
            expect(records.length).to.be(1);
            expect(records[0].intersectionRatio).to.be(0);
            expect(records[0].target).to.be(targetEl2);
            done();
          }, ASYNC_TIMEOUT);
},
```

Neither `targetEl1` nor `targetEl2` contain any pixels that intersect with `rootEl`. Why does the test expect an intersection observer callback for `targetEl2`?

cc @tobytailor

**Comment by mstange** [comment]
In particular, the spec says:

> callback will be invoked when intersectionRect’s area changes from greater than or equal to any threshold to less than that threshold, and vice versa.

and I don't understand how this justifies treating the two elements differently.

**Comment by philipwalton** [comment]
FYI, the discussion around this behavior is captured in #69.

**Comment by mstange** [comment]
Well, somewhat... as far as I can tell, the discussion does not mention requiring browsers to fire the callback when the element becomes adjacent to an edge. Even an `isIntersecting` flag would be false for both `targetEl1` and `targetEl2`, wouldn't it?

**Comment by philipwalton** [comment]
This [comment](https://github.com/WICG/IntersectionObserver/issues/69#issuecomment-180128037) in that thread describes the updated behavior:

> We think the spec should change to just invoke an inclusive intersection (includes the boundary points in the intersection).

In the test case you referenced above, `targetEl2` is on the boundary (though not overlapping) and `targetEl1` is not on the boundary (and also not overlapping). The use of inclusive intersections explains why an intersection is expected for `targetEl2`.

**Comment by mstange** [comment]
Ah, thank you. It wasn't clear to me whether that was just one idea of many, or an actual decision.
I'd appreciate the spec being updated, so that the tests can actually test specced behavior.
