### ISSUE TITLE
Specify what happens when an Element moves to a new document

### ISSUE THREAD

**Issue by smfr** [w3c/IntersectionObserver#166]
The spec should say what to do with IntersectionObservers when the target element moves between documents.

**Comment by szager-chromium** [comment]
I think this is covered by section 3.2.5:

http://wicg.github.io/IntersectionObserver/#update-intersection-observations-algo

Specifically:

"If the intersection root is not the implicit root and target is not a descendant of the intersection root in the containing block chain, skip further processing for target."

**Comment by smfr** [comment]
So if the intersection root is the implicit root, and the element moves to a new document (which is a child browsing context of the observer's browsing context), then the observer will continue to get notifications about it? Seems OK, if a little surprising.

**Comment by szager-chromium** [comment]
Yes, that's as intended.  In practice, we found that people were surprised when their observers stopped firing due to DOM modifications.

**Comment by miketaylr** [comment]
It sounds like this can be closed now.
