### ISSUE TITLE
Implicit root, the viewport, is not an Element

### ISSUE THREAD

**Issue by smfr** [w3c/IntersectionObserver#167]
> The intersection root for an IntersectionObserver is the value of its root attribute, or else the top-level browsing context’s viewport (referred to as the implicit root) if the root attribute is null.

This is confusing because 'root' is an Element, but the "top-level browsing context’s viewport" is a rectangle.

**Comment by szager-chromium** [comment]
Agreed, the implicit root should be the top-level document node.
