### ISSUE TITLE
Compute the Intersection of a Target Element and the Root steps unclear

### ISSUE THREAD

**Issue by smfr** [w3c/IntersectionObserver#169]
I don't think these steps are quite right:

> While container is not the intersection root:
> 1. Map intersectionRect to the coordinate space of container.
> 2. If container has overflow clipping or a css clip-path property, update intersectionRect by applying container’s clip.
> 3. If container is the root element of a nested browsing context, update container to be the browsing context container of container. Otherwise, update container to be the parent node of container.

I think there are two issues:

This walks the parent node chain, but needs to walk containing block chain to avoid non-containing-block ancestors with clipping from affecting the intersection:

`<div id="root" style="position: relative">
    <div style="overflow: hidden">
      <div id="target" style="position: absolute">This is not clipped</div></div></div>
`

Step 3 only applies if the root is the implicit root, I think (otherwise target and root are in different documents and you never got here). But I don't think this algorithm takes clipping by the iframe's viewport into account.

**Comment by szager-chromium** [comment]
Agreed about the ancestry walk, it should only apply clipping along the containing block chain.

As for iframe clipping: I think the clipping would be applied by the iframe element itself, no?

**Comment by smfr** [comment]
> As for iframe clipping: I think the clipping would be applied by the iframe element itself, no?

Yes but I don't think this would be covered by "container has overflow clipping" since it's not strictly CSS overflow clipping.
