### ISSUE TITLE
Polyfill: Check for intersection on animationend/transitionend

### ISSUE THREAD

**Issue by bdadam** [w3c/IntersectionObserver#213]
I think it would be an improvement to the polyfill to do the intersection check on animationend/transitionend events as well. These checks would not happen too often, therefore they are safe and cheap to do.

I created a PR for this change: https://github.com/WICG/IntersectionObserver/pull/212

**Comment by miketaylr** [comment]
The PR was closed due to inactivity. I propose we do the same here, but feel free to comment and we can re-open if there's further interest. Thanks.
