### ISSUE TITLE
Clarify if entry is created when starting to observe non-intersecting element

### ISSUE THREAD

**Issue by simevidas** [w3c/IntersectionObserver#214]
When starting to observe a bunch of images on the page, Chrome will create an `IntersectionObserverEntry` for every such image, and pass it to the callback, whereas Firefox will only do that for the images that are actually intersecting. Could you clarify what the correct behavior is?

Discussion and demo: https://twitter.com/alex_gibson/status/865330256651182081

**Comment by szager-chromium** [comment]
Take a look at issue #165 for more info.  Basically, Chrome supports a recent change to the spec where an initial notification is always sent, whether the target is intersecting or not.  Firefox doesn't do that, and it's not clear yet what they plan to ship.
