### ISSUE TITLE
Polyfill: callback is called synchronously

### ISSUE THREAD

**Issue by Jessidhia** [w3c/IntersectionObserver#225]
The intersection observer's callback should be called asynchronously according to spec.

https://wicg.github.io/IntersectionObserver/#update-intersection-observations-algo step 2.12

https://wicg.github.io/IntersectionObserver/#queue-an-intersectionobserverentry step 3

https://wicg.github.io/IntersectionObserver/#queue-intersection-observer-task step 3

The `this._callback` invocation should be done in a `requestIdleCallback` or `setTimeout` call.

**Comment by josephliccini** [comment]
I am getting an issue where both in IE and FireFox, when the polyfill is added, it quickly freezes up the page and the browser goes into "not responding". Would this synchronous callback create this behavior?

**Comment by Rendez** [comment]
I haven't been able to test extensively so I didn't experience a freeze up of the page in my case with several IO targets running. I am however using `requestIdleCallback` which indeed seems to be the best way to prevent potential "jank". To wrap your individual invocations, here's a snippet you can use for the time-being:

```js
import { requestIdleCallback } from 'request-idle-callback'; // opt-in polyfill

const hasNativeSupport = 'IntersectionObserver' in global && global.IntersectionObserver.prototype.toString() === '[object IntersectionObserver]';

const ensureAsync = (callback) => hasNativeSupport ? callback : (...args) => requestIdleCallback(callback.bind(undefined, ...args));

export default ensureAsync;
```

**Comment by miketaylr** [comment]
Given Firefox's native implementation, I'm going to optimistically close this issue. https://github.com/mlisook/plastic-image/issues/19#issuecomment-321393991 is also positive to see. If someone is still experiencing an issue, please comment and we can re-open.
