### ISSUE TITLE
Polyfill: Chrome uses Polyfill instead of native code

### ISSUE THREAD

**Issue by jesusbotella** [w3c/IntersectionObserver#234]
Hello,

I have just started using Intersection Observer to improve the performance of my web, and I noticed that if I import the polyfill in Chrome it is always used, instead of the native code.

The reason why it is always used is because of the condition used to determine if it should be loaded or not. It checks if the property [`intersectionRatio` exists in `IntersectionObserverEntry` prototype](https://github.com/WICG/IntersectionObserver/blob/gh-pages/polyfill/intersection-observer.js#L25), and it is evaluated to false.

What I see in [Intersection Observer Entry docs on MDN](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry) is that the intersectionRatio property is available from Chrome 51, and I am currently using Chrome 60. So I don't know why the value is false.

Should the condition be changed in order not to load the polyfill in Chrome?

Thank you!

**Comment by philipwalton** [comment]
What makes you say it's evaluated to false? The condition evaluates to true for me in Chrome and the native version is used.

**Comment by jesusbotella** [comment]
Yes, I'm sorry, the condition evaluates to true in a chrome blank window, but I'm bundling the polyfill inside another package. I think that due to JS hoisting and the IntersectionObserverEntry definition below, when I try to evaluate `'intersectionRatio' in IntersectionObserverEntry.prototype` just before evaluating the if condition, it is evaluated to false.

However, if you check if there exists `'intersectionRatio' in window.IntersectionObserverEntry.prototype`, it is true because you are checking it with the global definition of the IntersectionObserverEntry. I tried to modify it, and it works as expected.

I don't know if I'm missing something, but I think that it could be the reason why it was failing. 

If you think I'm correct, I'd be happy with making a PR to fix the code, or feel free to do it yourself if better.

**Comment by samouss** [comment]
I agree with @jesusbotella, [the recent changes](https://github.com/WICG/IntersectionObserver/commit/d4a699cc7a2d12e4e67cd6d1e748bed8bb6e3d8c#diff-d881855d8287e00bed364a1cee1dd6b6) on the polyfill update the condition.

**Comment by philipwalton** [comment]
@nolanlawson, sounds like this is related to the change in your PR (#224). Can you PTAL? I'm OOO for the next two weeks so I won't have time to dig into it.

**Comment by pottedmeat** [comment]
The root cause of this is, in JavaScript, named functions (`function Foo`) are available out-of-order and so `IntersectionObserverEntry` is referencing the function declared below it which does not have that property available on its prototype.

**Comment by Rendez** [comment]
Also agree with @jesusbotella's your explanation is clear. Most package bundles - I am using webpack atm - emulate modules using function closures, therefore causing the hoisting. The 3rd IF check is wrongly positive for Chrome. Haven't tried other browsers yet but the behaviour is potentially the same.

![screen shot 2017-08-10 at 16 36 44](https://user-images.githubusercontent.com/61776/29175929-b6bfe624-7dea-11e7-897c-f8b13dfbd495.png)

Don't mean to sounds repetitive here; this should patched be adding back `'intersectionRatio' in window.IntersectionObserverEntry.prototype` statement.

**Comment by jesusbotella** [comment]
@nolanlawson @philipwalton Could you please take a look to the created pull requests to accept one of them, or fix the issue, whenever you can? :)

I don't know which one is more likely to be accepted, but I think @pottedmeat's change is better, according to the current code structure.

**Comment by philipwalton** [comment]
This should be fixed in version `0.4.1`. Sorry for taking a while to get to it; the post-vacation backlog was larger than expected :)

**Comment by jesusbotella** [comment]
Thank you very much! 🎉
