### ISSUE TITLE
Not working working for safari/IE

### ISSUE THREAD

**Issue by maaizelahi** [w3c/IntersectionObserver#236]
I am using the polyfill to detect whether the element is in view or not. But it doesn't seems to be working on IE and Safari

**Comment by radeno** [comment]
Same as in #206. But that fix doesn't help.

In window is just IntersectionObserverEntry.

Safari 10.1.2.

**Comment by radeno** [comment]
Taking back, for Safari it works, my mistake about bad calling.

**Comment by philipwalton** [comment]
Can you please be more specific about what's not working? Also, can you confirm you're testing against the latest version of the polyfill?

**Comment by maaizelahi** [comment]
Interaction observer callback is not firing correctly in case of iframes.

I am observing an element within the same domain/cross domain iframe. In either case the Interaction observer callback is not getting called at the specified thresholds.

I am using the polyfill url 
<script src="https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver"></script>
which I believe is pointing to the latest polyfill

**Comment by philipwalton** [comment]
Ahh, yes, currently the polyfill doesn't support iframes. We may add support for some limited cases in the future, but nothing is planned at the moment.
