### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/IntersectionObserver#241]
Would you like time to update the WebPlat WG on this spec and/or discuss any relevant topics at TPAC? We have space on the WebPlat agenda on Thursday and Friday of TPAC week.

If yes, could you estimate the time you'd like/need (in 30 minute blocks)? Thanks

**Comment by szager-chromium** [comment]
I guess this is addressed to me?  Sure, I can do that.   I don't think I'll need more than 30 minutes.

**Comment by mkruisselbrink** [comment]
It seems to be on the [agenda](https://github.com/w3c/WebPlatformWG/issues/94)?

**Comment by szager-chromium** [comment]
Thanks!
