### ISSUE TITLE
Use requestAnimationFrame when THROTTLE_TIMEOUT is 0

### ISSUE THREAD

**Issue by pottedmeat** [w3c/IntersectionObserver#248]
To match the native API as closely as possible, calculations should be performed in a `requestAnimationFrame` callback. Because calculations are expensive when done in a polyfill, `requestAnimationFrame` should only be used when `THROTTLE_TIMEOUT` is 0.

**Comment by miketaylr** [comment]
The rAF approach was abandoned in https://github.com/w3c/IntersectionObserver/pull/249#issuecomment-329257683, so I propose we close here. If someone would like to pick this up again, please leave a comment and we can re-open.
