### ISSUE TITLE
CFC: Publish the First Public Working Draft (FPWD) of Intersection Observer

### ISSUE THREAD

**Issue by LJWatson** [w3c/IntersectionObserver#250]
This is a Call For Consensus (CFC) to publish the FPWD of Intersection Observer, based on the current [Editor's Draft](https://w3c.github.io/IntersectionObserver/)

Please respond to this CFC by the end of day on Friday 8th September 2017. If you choose not to respond to this CFC it will be taken as implicit support
for the proposal. Your opinion is important though, so please indicate your response by adding a thumbs up/down to this comment (and if you opt for thumbs down, please explain why.

**Comment by szager-chromium** [comment]
I support publishing the working draft.  IntersectionObserver has already shipped in Chrome/Opera, Firefox, and Edge, and it is in active development in WebKit.  Thus, it is rapidly becoming a de facto standard.  It is also quite popular; in Chrome, IntersectionObserver is used in ~1.75% of all page views:

https://www.chromestatus.com/metrics/feature/timeline/popularity/1368

The early development of the IntersectionObserver spec is, I think, a success story for the incubator group model.  Now, it's time to close the loop and move it onto the formal standards track.

**Comment by tobytailor** [comment]
I support publishing the working draft as well. We ship a compliant implementation since Firefox 55.

**Comment by LJWatson** [comment]
With thanks to everyone who responded, this CFC passes with multiple expressions of support and no objections.

I'll put through the transition request to publish the FPWD of Intersection Observer.
