### ISSUE TITLE
Problem of callback with respect to 'threshold' value.

### ISSUE THREAD

**Issue by ultimatecoder** [w3c/IntersectionObserver#253]
* **Description:** I am trying to understand the IntersectionObserver API by implementing a small example. In my example, even if I specify the 'threshold' value to 1.0, it is called anyhow after the load event and then called back again when my element is visible. I am very much confused about this behavior.

* **Questions:**
* Why is the callback called after load? It should be only called once the element which I am observing is intersecting my root element.
* Am I doing any mistake in defining the CSS and HTML structure to test this code?

* **Fiddle:** https://jsfiddle.net/fxa2o5pw/2/

If the example is right than Is this a thing to improve?

**Comment by farhaanbukhsh** [comment]
So it is working perfectly fine, threshold 1 being when the element is visible so your element is visible on the load of the page.

Let's make it work, fill in Loren Ipsum and make it a scrollable page and try it out again you will see the change.

**Comment by philipwalton** [comment]
>  it is called anyhow after the load event and then called back again when my element is visible. I am very much confused about this behavior.

I'm only seeing a single call. What browser are you using?

Also, FWIW, the callback is always invoked after the `observe()` method is invoked with the initial intersection status. It's then called again once the intersection status changes. In your example, it should only be called once as soon as `.observe()` is invoked.

**Comment by ultimatecoder** [comment]
@farhaanbukhsh Many thanks for replying here. I have added text and still facing that exact problem. Can you create JSFiddle and share? It will take less amount of time if you fork what I did.

**Comment by ultimatecoder** [comment]
@philipwalton I am using Google Chrome "Version 60.0.3112.101 (Official Build) (64-bit)" under Ubuntu 16.04 LTS operating system.

If the callback should be invoked after the `.observe()` then the behaviour I am getting is acceptable, but such behaviour is not mentioned at https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/observe I am apologised if I am following the wrong reference. 

Below are the detailed steps and behaviour I am getting while triaging with my js-fiddle example:

1. I press run button
2. I am getting the alert popup. Which is coming from `my_callback()` function.  
3. I scroll down using down button of the "#main-div". When my "#box" visible (from #main-div), I am getting popup coming from my `my_callback()`.
4. I scroll up and again the popup is fired from `my_callback()`.

Problem

* **Step-2**: Should I get popup in step `2`? The`threshold` value I have provided is `1.0` which means it should only call a callback when `observing element (which is #box in this example)` is intersecting with `root(which is #main-div in this example)` element. Such behaviour is expected at `step-3` because an observed element is intersecting with root. If the `thresold` value was `0.0` then too, getting popup at `step-2` is not according to docs.

**Comment by philipwalton** [comment]
Yes, it looks like mdn is not correct here (or at least not clear). The [relevant section of the spec for the `observe()` method](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserver-observe) is:

> Let intersectionObserverRegistration be an IntersectionObserverRegistration record with an observer property set to this, a previousThresholdIndex property set to -1, and a previousIsIntersecting property set to false.

By setting the `previousThresholdIndex` to `-1`, you guarantee that a callback will be queued immediately (since thresholds otherwise always compute to a value between 0 and 1, a -1 value will always trigger a change in intersection status).

**Comment by philipwalton** [comment]
> Problem

> **Step-2:** Should I get popup in step 2? Thethreshold value I have provided is 1.0 which means it should only call a callback when observing element (which is #box in this example) is intersecting with root(which is #main-div in this example) element. Such behaviour is expected at step-3 because an observed element is intersecting with root. If the thresold value was 0.0 then too, getting popup at step-2 is not according to docs.

Everything that I'm seeing in your example is correct and exactly what'd I'd expect.

Keep in mind that `my_callback()` isn't just invoked when the element is visible, it's invoked whenever the element's intersection status changes. This means it can be invoked in three situations:

1) As soon as you start observing (as I mentioned previously)
2) When it goes from not intersecting to intersecting (hidden to visible)
3) When it goes from intersecting to not intersecting (visible to hidden)
