### ISSUE TITLE
Not working in Safari: IntersectionRect properties are 0

### ISSUE THREAD

**Issue by jamesAtcodeninja** [w3c/IntersectionObserver#254]
<img width="1010" alt="chrome" src="https://user-images.githubusercontent.com/26530591/30247274-1978f146-9643-11e7-998c-16e897e6ffc7.png">
<img width="699" alt="safari" src="https://user-images.githubusercontent.com/26530591/30247275-197b242a-9643-11e7-8b08-7035a8d2814c.png">
Changes are not observed in Safari, and my guess is this is due to the IntesectionRect not getting its properties defined. Polyfill works in Firefox however.

**Comment by philipwalton** [comment]
@jamesAtcodeninja is this related to your comment here? https://github.com/w3c/IntersectionObserver/issues/206#issuecomment-328038311

If so, you're likely using an old version. Can you verify you're on the latest version and confirm whether this is still an issue? And if it is, please post a reduced test case as the screenshot you uploaded doesn't give enough information to reproduce the issue.

**Comment by jamesAtcodeninja** [comment]
I'm using version `0.4.2` of intersection-observer and `10.1.2`.
The polyfill is used by `vue-observe-visibility`, and works in Chrome and Firefox.

**Comment by maxval94** [comment]
I have the same problem http://joxi.ru/KAgoOWgI4RgjPA

**Comment by jamesAtcodeninja** [comment]
I'm using intersection-observer version `0.5.0`, and it's working fine for me. Safari version is `Version 11.0.1 (12604.3.5.1.1)`.

**Comment by jordilopez** [comment]
If you're `root` element is the viewport (default), make sure `body` and `html` have a `height` value, `100%` or whatever. 

`rootBounds.height` maybe is correct, but the element's height is still considered `0px`.

![image](https://user-images.githubusercontent.com/1140361/40180983-5a6a12ac-59e8-11e8-9109-08af72f848c2.png)

**Comment by miketaylr** [comment]
> I have the same problem http://joxi.ru/KAgoOWgI4RgjPA

Unfortunately this is 404 now. Given that the has evolved a bit, let's optimistically close this issue. If someone can still reproduce, please leave a comment and we can re-open if needed.

**Comment by Zannick** [comment]
I can reproduce this. I'm attaching bootstrap popovers to svg `g` elements, and using IntersectionObserver to close the popover when they scroll out of view. However, in Safari and Epiphany, `boundingClientRect` has 0 width and 0 height, so `intersectionRect` is all 0 right away. This means my code immediately hides the popover. I haven't been able to debug why the observer thinks my element has no width, but I did manage to recreate in a minimal html:

```html
<html>
    <head>
        <style>
        #game g.cinfo {font-size: 32px;font-weight: bold;text-anchor: middle;position:absolute;}
        .offset {transform: translate(25px, 40px);}
        text {fill: #000;font-family: sans-serif;}
        </style>
    </head>
    <body>
        <div id="main">
            <div id="game">
                <svg height="100%" version="1.1" width="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 100 100" class="board overlay main">
                    <g fill="#ff0f0f" href="#" role="button" class="cinfo help offset"><circle cx="0" cy="0" r="18"></circle><text x="0" y="11">?</text></g>
                </svg>
            </div>
        </div>
    </body>
    <script type="text/javascript">
        function reportEntries(entries, obs) {
            console.log(entries[0]);
            console.log(entries[0].intersectionRect);
            console.log(entries[0].target.getBoundingClientRect());
        }
        var observer = new IntersectionObserver(reportEntries, {
            root: document.querySelector('#game'),
            threshold: 0.5,
        });
        observer.observe(document.querySelector('g.cinfo'));
    </script>
</html>
```

using Epiphany 49.2 (Nov 2025) on Fedora 43.

My workaround for my particular use case is to check that the boundingClientRect width is nonzero to prevent hiding on the initial appearance, but as the width and height are always calculated as 0, I can never truly detect when visibility changes, so I only lose the ability to hide the popovers automatically in this way.
