### ISSUE TITLE
documentElement.clientHeight returns full content height

### ISSUE THREAD

**Issue by CruelMoney** [w3c/IntersectionObserver#257]
When using the polyfill my entries always have an intersectionRatio of 1. I've just spend some time debugging it, and after some time I figured the problem is in the following part of `_getRootRect()`:

````
...
 // Use <html>/<body> instead of window since scroll bars affect size.
    var html = document.documentElement;
    var body = document.body;
    rootRect = {
      top: 0,
      left: 0,
      right: html.clientWidth || body.clientWidth,
      width: html.clientWidth || body.clientWidth,
      bottom: html.clientHeight || body.clientHeight,
      height: html.clientHeight || body.clientHeight
    };
...
````
It defaults to use document.documentElement.clientHeight which in my case returns the full height of all content, whereas document.body.clientHeight will return the height of the viewport (which I guess is the intention). 
Switching to prefer body over documentElement, makes the polyfill work for me. Can anyone ellaborate on why to use documentElement?

**Comment by nekuz0r** [comment]
Applying `height: 100%` on `html` element seems to make `document.documentElement.clientHeight` to return correct value.

I didn't test on `width` but i guess it will works too.

**Comment by philipwalton** [comment]
@CruelMoney can you share a link to the site where you're seeing this? In my experience the vast majority of sites will report the `<html>` element having the same dimensions as the document and `<body>` will report the full dimensions of all the content.

**Comment by CruelMoney** [comment]
@philipwalton [My personal website](https://cude.io/). 

Haven't tried to set `height: 100%` on the html element, as I ended up changing the source code.

**Comment by philipwalton** [comment]
Thanks, you're definitely doing some unusual things with layout there :) but I guess it shows that `document.documentElement.clientWidth/Height` isn't foolproof, so I may go back to using `window.innerHeight/Width` (which I was originally using, but switched because it didn't include scrollbars).

**Comment by Yaffle** [comment]
@CruelMoney, you have no doctype declaration and so the "quirks mode". try to add:
```
<!DOCTYPE html>
```

**Comment by onigoetz** [comment]
Thank you @Yaffle This did the trick on a bug we were tracking down in an example application :)

**Comment by nabtron** [comment]
@Yaffle you are awesome! Didn't even think about this mistake! How can I donate you?

**Comment by miketaylr** [comment]
I'm going to declare handling quirksmode to be out of scope. Doctypes are cool. :) Let's close here.

**Comment by Mouradouchane** [comment]
hi , i faced the same problem just a few hours ago  , and i notice when i put 
```css
body{
    position : absolute ;
    height : 100% ;
}
```
then clientHeight will works 🤔
