### ISSUE TITLE
IntersectionObserver doesn’t fire w/ animations

### ISSUE THREAD

**Issue by surma** [w3c/IntersectionObserver#262]
At first I thought this was a Chrome bug, but Firefox exhibits the exact same behavior so I am _assuming_ it’s a spec bug. Please help me triage.

Demo: https://io-raf-bug.glitch.me/
Code: https://glitch.com/edit/#!/io-raf-bug?path=index.html

Steps:
1. Open the [demo] and don’t move the mouse or trigger any other form of event. The text in the blue box does not update (or at least not consistently).
2. Move the mouse frantically to see the blue box update
3. Click the “With raF” link
4. Repeat step 1 and see the blue box update consistently

“With rAF” just runs an _empty_ function on every frame:
```js
    requestAnimationFrame(function f() {
      requestAnimationFrame(f);
    })
```

I feel like IOs should fire for animations without any sort of workaround.

[demo]: https://io-raf-bug.glitch.me/

(cc @notwaldorf)

**Comment by zzebastien** [comment]
+1

**Comment by bloep** [comment]
+1
In Firefox 56.0 (64-Bit) on Linux it also doesn't seem to work with rAF, too.

**Comment by szager-chromium** [comment]
In the case of chromium, because the animation runs completely in the compositor, no frames are being generated in blink.  I would guess that the same is true in firefox.

AFAIK, the HTML spec has nothing to say about compositor animations.  I think this is actually a bug in both chromium in firefox, not a bug in the spec.

**Comment by surma** [comment]
I’ll wait till after TPAC to open bugs on FF and Chrome :)

**Comment by surma** [comment]
Ping. Should I open bugs on FF and Chrome?

**Comment by szager-chromium** [comment]
Yes, this is clearly an implementation bug.

**Comment by surma** [comment]
Crbug: https://crbug.com/787364
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1419339
