### ISSUE TITLE
polyfill version - no tag released

### ISSUE THREAD

**Issue by zzebastien** [w3c/IntersectionObserver#264]
Hi,
there is no tag in the github repo for the polyfill, could you please create one ?

The package.json mention the version "0.4.2" : https://github.com/w3c/IntersectionObserver/blob/master/polyfill/package.json

... but there is no tag for this version, so if I want to use npm I don't want to use the master or any other branch, I would prefer to use a specific tag version for consistency.

Thanks!
And keep-up the good job, the polyfill works very well.

**Comment by philipwalton** [comment]
The reason I didn't include a tag is because tags apply to the entire repo, and I didn't want there to be confusion between the version of the polyfill and the version of the spec.

Out of curiosity, why are you wanting to install from Github rather than from npm? The files should be identical.

**Comment by zzebastien** [comment]
you're right, I don't know why I would use github instead of npm, I'm closing this issue, sorry for the interruption!
