### ISSUE TITLE
Layout viewport vs visual viewport

### ISSUE THREAD

**Issue by nolanlawson** [w3c/IntersectionObserver#266]
Currently in the spec it says:

> Note: Root intersection rectangle is not affected by pinch zoom and will report the unadjusted viewport, consistent with the intent of pinch zooming (to act like a magnifying glass and NOT change layout.)

This seems to imply that the default root is the layout viewport, not the visual viewport.

However, during TPAC 2017, the Web Perf WG discussed [Element Timing](https://docs.google.com/presentation/d/1Xha-RVH_bz5mzOHi1wI5BT8AEaLd-fSYW4BKpmJmy5A/edit) ([notes](https://docs.google.com/document/d/1s7S1gpAp4nzFclIHN_nxN84Rfz-LMV554gf2-8aXR10/edit#)) and came to the conclusion that it would be useful to define Element Timing in terms of Intersection Observer (as a "declarative Intersection Observer"). This doesn't seem possible, however, if the default root is the layout viewport, and there's no way to use the visual viewport instead.

Should IntersectionObserver allow using either the layout viewport or the visual viewport as the root? Alternatively, is "layout viewport by default" the behavior we want?

**Comment by nolanlawson** [comment]
This discussion came up again as we're updating our implementation. The visual viewport seems to make the most sense, especially for things like Hero/Element Timing polyfills (e.g. @tdresser's polyfill [here](https://github.com/tdresser/hero-element-polyfill/blob/9f9bfef6e333bebca9952251b26985168da47d3b/hero_element_timing.js#L11).) However, we're currently planning to stick with the layout viewport for compatibility reasons.

Do other UAs intend to stick with the layout viewport?

**Comment by tdresser** [comment]
@ojanvafai @bokand

**Comment by bokand** [comment]
IIRC, Edge currently uses the visual viewport. We definitely should either align with them or add the option to use visual. @szager-chromium

**Comment by ojanvafai** [comment]
Sorry, it turns out I misspoke at TPAC. I thought we had resolved this by adding an option to choose whether you want visual or layout. Didn't remember it got stuck on the question for which one should be the default. 

https://github.com/w3c/IntersectionObserver/issues/95 is where the discussion for this is. Should we dupe this to that issue?

**Comment by zcorpan** [comment]
This issue came up in the discussion for `<img loading=lazy>` https://github.com/whatwg/html/issues/5408#issuecomment-623683336

**Comment by miketaylr** [comment]
> #95 is where the discussion for this is. Should we dupe this to that issue?

Yes
