### ISSUE TITLE
Master vs gh-pages?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IntersectionObserver#269]
Having both branches causes confusion. We should trash one or the other.

**Comment by philipwalton** [comment]
I think we should remove the `gh-pages` branch since Github now supports hosting Github Pages from the master branch. Also, [from the diff](https://github.com/w3c/IntersectionObserver/compare/gh-pages...master), it looks like the `master` branch is more up-to-date.

AFAICT, what needs to happen is:

1. An `index.html` file needs to be generated on the master branch
2. The Github Pages section under https://github.com/w3c/IntersectionObserver/settings needs to be changed to `master`
3. The `gh-pages` branch needs to be deleted.

@szager-chromium, are you able to do this?

**Comment by szager-chromium** [comment]
Nope, I cannot do it:

$ git push --force origin :refs/heads/gh-pages
Username for 'https://github.com': szager-chromium
Password for 'https://szager-chromium@github.com': 
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.
remote: error: Cannot delete a protected branch
To https://github.com/w3c/IntersectionObserver.git
 ! [remote rejected] gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/w3c/IntersectionObserver.git'

**Comment by szager-chromium** [comment]
I'm going to just delete everything but a README saying "Don't use this branch."

**Comment by szager-chromium** [comment]
Done.

**Comment by philipwalton** [comment]
Wait, (1) and (2) above need to be done because now this page is broken: https://w3c.github.io/IntersectionObserver/

**Comment by szager-chromium** [comment]
As I understand it, index.html will be auto-generated by w3c's travis-CI, so we don't need to have index.html in the repository.

I did (2) already; I think it may just need some time to catch up.

**Comment by szager-chromium** [comment]
@siusin, can you confirm that travis-CI will generate index.html?  Where is it served from?

**Comment by philipwalton** [comment]
Ok, I [reverted the gh-pages commit](752b1956e4b3f61b45832dd62b048cfa5408e297) to at least get the spec back up, so maybe that was a mistake.

I'll let someone who knows how the automated stuff is set up handle this :)

**Comment by LJWatson** [comment]
Ping @siusin

**Comment by siusin** [comment]
With the `deploy.sh` script in the repo, once people commit changes to `master` branch, travis.ci will build an html document with the latest version of Bikeshed and push this document to `gh-pages`.

If we want to keep only one branch, i.e. the source branch is the same as the output branch, every time people commit a change to the `master`, travis.ci will do a new commit to master again after the build. That will make the remote contains work that people do not have locally. Do you think this will bring exact work for you? 

IMO the [auto-deploy script](https://github.com/w3c/IntersectionObserver/blob/master/deploy.sh) won't make much sense if there is only one branch and if people are willing to make sure the `.html` document in sync with the `.bs` file before they do a commit.

**Comment by plehegar** [comment]
was this issue resolved with the new deployment procedures? I can't figure out if things are fine now.

**Comment by philipwalton** [comment]
It wasn't resolved, but I [updated `deploy.sh`](https://github.com/w3c/IntersectionObserver/commit/5b129a921fdcae91f61f747e2e7e846169ec030c) and it looks like it's resolved now.

The previous version of the script kept the polyfill and other files in the `gh-pages` branch when publishing, which made those branches mostly identical and thus caused the confusion. Now that `gh-pages` just contains the `index.html` file, I think things should be fine.
