### ISSUE TITLE
Polyfill: intersectionRatio wrong if root has border

### ISSUE THREAD

**Issue by waldbaerkoch** [w3c/IntersectionObserver#276]
See the following HTML doc. The root (here the `div` element with `id="outer"`) has a border (`border: 2px solid #000`). That results in calculating the wrong `intersectionRatio` for the second observed element (`div` element with `id="el2"`). Only the first observed element should get the `class` "visible".

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script>
delete window.IntersectionObserver;
    </script>
    <script src="intersection-observer.js"></script>
    <script>
function init() {
  function callback(entries, observer) {
    Array.prototype.forEach.call(entries, function(entry) {
      if (entry.intersectionRatio > 0) {
        entry.target.classList.add('visible');
      }
    });
  }
  var observer = new IntersectionObserver(callback, { root: document.getElementById('outer') });
  Array.prototype.forEach.call(document.querySelectorAll('#outer div'), function(el) {
    observer.observe(el);
  });
}
window.addEventListener('load', init);
    </script>
    <style>
#outer {
  overflow-y: hidden;
  height: 2em;
  border: 2px solid #000;
}
#outer div {
  height: 100%;
}
    </style>
  </head>
  <body>
    <div id="outer">
      <div id="el1">Element 1</div>
      <div id="el2">Element 2</div>
      <div id="el3">Element 3</div>
    </div>
  </body>
</html>
```

I cross-checked with Chrome, Firefox and Edge (with the `delete window.IntersectionObserver;` removed). In all three only `el1` has the `class` "visible".

**Comment by waldbaerkoch** [comment]
The intersection returned by `IntersectionObserver.prototype._computeTargetAndRootIntersection()` is computed using `DOMRect` objects obtained by `getBoundingClientRect()`, which according to https://www.w3.org/TR/cssom-view/#dom-element-getclientrects step 3 describes the _border area_.

Should the `parentRext` passed to the `computeRectIntersection()` function be reduced by the root's border?

**Comment by miketaylr** [comment]
The polyfill is being removed in https://github.com/w3c/IntersectionObserver/pull/499 (see #433 for discussion). 

If you can still reproduce bugs in the native implementations, filing bugs in the various bug tracks would be really helpful.

I'm going to close this as wontfix, but thanks for taking the time to report this issue!
