### ISSUE TITLE
Since v4.0.1 the threshold option doesn't work in Firefox

### ISSUE THREAD

**Issue by cowardcalf** [w3c/IntersectionObserver#284]
Although I've initialised the IO with threshold containing a series values, it triggers only when the target enter in or leave out of the viewport.
And the intersecting ratio is always 1.

So far, it is like that in Firefox only. 
Chrome and Safari are fine.

**Comment by szager-chromium** [comment]
Please file a bug against firefox:

https://bugzilla.mozilla.org/

**Comment by cowardcalf** [comment]
Looking like it has been fixed
