### ISSUE TITLE
Not working with Edge 40 Windows Phone (Windows 8.1)

### ISSUE THREAD

**Issue by swisstofu** [w3c/IntersectionObserver#285]
No images are displayed. it occurs that if i force polyfill for browser. not really a good fix but i don't have something better to propose yet.

Any idea ?

https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L20-L30

```
// Minimal polyfill for Edge 15's lack of `isIntersecting`
// See: https://github.com/w3c/IntersectionObserver/issues/211
if ('isIntersecting' in window.IntersectionObserverEntry.prototype)) {
  return;
}
Object.defineProperty(window.IntersectionObserverEntry.prototype,
   'isIntersecting', {
      get: function () {
        return this.intersectionRatio > 0;
      }
  });
}
```

**Comment by szager-chromium** [comment]
Please file a bug against Edge:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
