### ISSUE TITLE
Intersection calculation for absolute positioned elements seems to be incorrect using the Polyfill

### ISSUE THREAD

**Issue by thasmo** [w3c/IntersectionObserver#286]
It seems that intersection calculation/determination (of the polyfill) for observed elements, which are positioned absolute, is not always working correctly as the callback is triggered for some of these elements but not for all, in my case. (Polling also doesn't help.)

When setting `position` to `relative`, the callback gets triggered correctly for all elements.

I've tried to find relevant Github issues but I'm not sure any related ones exist yet.

Is this a known issue?

**Comment by philipwalton** [comment]
Can you provide a demo showing the problem? The tests for the polyfill are all run using absolutely positioned elements, so it definitely *does* work in some cases.

**Comment by shawnnaquin** [comment]
#315 is related

**Comment by miketaylr** [comment]
Going to close here due to a lack of a minimized test case, or more info on browsers or versions (and #315 is closed now too). If someone can provide that, we can re-open. Thanks.
