### ISSUE TITLE
isIntersecting returns incorrect result in the Chrome at low values of the intersectionRatio

### ISSUE THREAD

**Issue by Kesantielu** [w3c/IntersectionObserver#287]
In Chrome at low values of `intersectionRatio`, it rounds down to `0`, and the polyfill returns `isIntersecting: false` .
The native implementation of `isIntersecting `property returns the correct value `isIntersecting: true`.

**Comment by philipwalton** [comment]
Chrome supports this API natively, so can you clarify whether you're actually running the polyfill in chrome? If you are, what's the use case for that?

**Comment by Yimiprod** [comment]
Here's an example, with `rootMargin` using thoses values `0% -50%` meaning center box.
https://jsfiddle.net/rh9y7Lxs/10/

On some browsers (sometime chrome does it too), `intersectionRatio` will equal `0` meaning `isIntersecting` couldn't be true.

**Comment by miketaylr** [comment]
Given that the polyfill should bail when a native implementation is supported (https://github.com/w3c/IntersectionObserver/blob/main/polyfill/intersection-observer.js#L17-L21), I'm not sure this report is valid.

I could be misunderstanding, so if someone can provide more clarity on _which_ browsers (and versions) this issue reproduces on, we can re-open. Thanks.
