### ISSUE TITLE
Polyfill not suitable for universal / isomorphic app

### ISSUE THREAD

**Issue by scoobster17** [w3c/IntersectionObserver#292]
It seems that because of the way the polyfill has been written, using an IIFE that uses `window` as it's (unchangable) argument, that when this polyfill is used in a universal react app, say, when the code is built server side, the `require` when used as per [this repo's polyfill README](https://github.com/w3c/IntersectionObserver/tree/master/polyfill) throws a `ReferenceError: window is not defined` error:

```
require('intersection-observer');
```

I'm not saying we should start worrying about making this work for `node`, but I think it would be sensible for this use case to check if `window` exists? And if not, do nothing. This simple fix would mean this polyfill will work in universal apps too.

**Comment by chrstntdd** [comment]
I've had this same issue, but have found a temporary solution. There's an open PR to add support for SSR and I've added my temporary solution there: https://github.com/w3c/IntersectionObserver/pull/279#issuecomment-382741031
Hope this helps!

**Comment by scoobster17** [comment]
Thanks, I don't know why that didn't come up in my searches. I have found a solution for what I am building (not a comprehensive polyfill, but a minimalistic one tailored for it's purpose). I'll bear it in mind for the future though!

**Comment by philipwalton** [comment]
Let's keep the discussion around this issue in #279.
