### ISSUE TITLE
how to detect browser support for IntersectionObserver to avoid load

### ISSUE THREAD

**Issue by puppetmaster3** [w3c/IntersectionObserver#296]
How can I check if ( ! IntersectionObserver ) in javascript to see if browser supports it?

So I only load if not supported.

**Comment by midzer** [comment]
You can try something like
```javascript
if (!'IntersectionObserver' in window &&
    !'IntersectionObserverEntry' in window &&
    !'intersectionRatio' in window.IntersectionObserverEntry.prototype) {
    // load polyfill now
}
```

**Comment by nickion** [comment]
> if (!'IntersectionObserver' in window &&
>     !'IntersectionObserverEntry' in window &&
>     !'intersectionRatio' in window.IntersectionObserverEntry.prototype) {

Easy mistake to make, but because the intent is to fallback should any prerequisite not be satisfied || should be used rather than &&, i.e.  if we don't have this or we don't have that...),. Alternatively, use && with positive tests and negate the entire expression (we need this and that, and if we don't have all of them...).

**Comment by doughballs** [comment]
@midzer tested in Safari, doesn't work unfortunately. I put a simple console.log inside the brackets and it is not triggered.

@nickion using || generates the following error on line 3:

`TypeError: undefined is not an object (evaluating 'window.IntersectionObserverEntry.prototype')
`

**Comment by joselanderosmrf** [comment]
FYI, on some versions of Chrome, Opera and Edge IntersectionObservers are partially implemented so the check `'isIntersecting' in window.IntersectionObserverEntry.prototype` is also necessary to check for full support.

**Comment by Sebiworld** [comment]
@joselanderosmrf Or you use `entry.intersectionRatio > 0` to detect if an element is visible instead of `entry.isIntersecting`. As far as I know it only should bother IE Edge.

**Comment by lucidlive** [comment]
Just use the polyfill:

`<script src='https://cdn.polyfill.io/v2/polyfill.js?features=IntersectionObserver'></script>`
