### ISSUE TITLE
Invalid old IE event handler removal

### ISSUE THREAD

**Issue by philg-ygt** [w3c/IntersectionObserver#299]
`detatchEvent` does not exist:

https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L605

This means that no event handlers will be removed in old IE.

**Comment by miketaylr** [comment]
This was fixed in https://github.com/w3c/IntersectionObserver/commit/517613eae4896d9f53b869b66c8f7fea9012b4fe
