### ISSUE TITLE
IntesectionObserver fails to fire event upon horizontal scrolling on small screen

### ISSUE THREAD

**Issue by anatsarig** [w3c/IntersectionObserver#301]
When laying elements horizontally (with horizontal scroll bar), and scrolling left/right,
IntersectionObserver does not always fire event when an observed element enters the viewport.
This happens on mobile devices or when testing on desktop chrome while setting small dimensions or Responsive screen  or mobile screens (iPhone 6/7/8 etc.)

Is there a way to overcome this ?
Thank you

**Comment by szager-chromium** [comment]
This is most likely related to issue #266. If the layout viewport is bigger than the visual viewport, then IntersectionObserver won't send notifications when objects move on or off the screen.

This is not unique to horizontal scrolling; it should affect vertical scrolling the same way.

**Comment by anatsarig** [comment]
Will it be fixed in the near future ? Thank you

**Comment by bruscantini** [comment]
I'd also like to know. I'm having issues on safari probably because it's not using the visual viewport. Why can't we have it as an option?

**Comment by leonardojimenez** [comment]
+1, getting same issue on Chrome as well

**Comment by miketaylr** [comment]
Given https://github.com/w3c/IntersectionObserver/issues/301#issuecomment-395898386, let's close this issue as a duplicate. If someone has a reduced test case to show it's different, please command and we can re-open.
