### ISSUE TITLE
Problem when running safari locally

### ISSUE THREAD

**Issue by mackelito** [w3c/IntersectionObserver#302]
So this is really strange... it works in production and on staging but not on localhost (or 192.186.x.x)..
It works on local in all other browsers except for Safari!? (both desktop and on iOS 11)

This is my current code:

    const IntersectionObserverOptions = {
      // root: document.querySelector('.content'),
      rootMargin: '0px 0px 800px 0px',
      threshold: 0.0
    };
    this.iIntersectionObserver = new IntersectionObserver(entries => {
      if (entries[0].intersectionRatio <= 0) { return; }
      if (entries[0].isIntersecting) {
        this.iIntersectionObserver.unobserve(entries[0].target);
        this.loadMoreProducts.emit();
      }
    }, IntersectionObserverOptions);

removing this makes the site load properly..

Any ideas?

**Comment by simeyla** [comment]
Repro?

**Comment by szager-chromium** [comment]
This should be filed as a bug against WebKit at https://bugs.webkit.org/

**Comment by mackelito** [comment]
FYI this was due to missing POLL_INTERVAL setting... once set it worked locally.. but performance get's super bad when navigating the site...
