### ISSUE TITLE
iOS Safari intersectionRatio calculations do not respect self-hiding browser chrome

### ISSUE THREAD

**Issue by simeyla** [w3c/IntersectionObserver#305]
The default behavior in iOS Safari when you scroll down, is that the URL bar at the top becomes smaller, and the bottom toolbar disappears.

This leads to the height of the viewport being taller than it was. This polyfill does not observe this change and the intersectionRatio is not correctly calculated.

Side effects:

* An item being scrolled into view does not even reach 0% visibility until it is already about 70px into the viewport. So if using the API to trigger a 
* When scrolling up the page an item disappearing from view on the bottom of the screen is marked as out of view while it is still 70px visible.

Notes:

* When an item enters or leaves the top of the viewport the calculations are pixel perfect whichever direction you scroll.
* This behavior is NOT observed in [Stackblitz](https://ng-in-viewport-example.stackblitz.io/) projects because the toolbars don't contract.
* Even setting POLL_INTERVAL on my IntersectionObserver instance does not seem to be able to calculate it correctly.
* Chrome on Android works correctly, but only when you stop scrolling is the effect of a self-hiding menubar get factored into the calculations.

Repro:

The easiest way to reproduce is to create 10 divs of height 20px and create thresholds at .1, .2, .3 etc. to correspond to the divs with javascript to display the percentage. Then observe scrolling behavior at margins.

**Comment by benjaminpreiss** [comment]
I am having this issue as well but only when scrolling down strangely...

**Comment by miketaylr** [comment]
Given that iOS Safari has a native implementation now, I propose we close here.
