### ISSUE TITLE
IE8 not support Function.prototype.bind

### ISSUE THREAD

**Issue by santinoDu** [w3c/IntersectionObserver#312]
See https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L94
As IE7 or IE8 do not support Function.prototype.bind, this IntersectionObserver polyfill will not work in IE7 or IE8.

**Comment by santinoDu** [comment]
Also find some methods not support by IE8: getComputedStyle, Array.prototype.forEach, Array.prototype.indexOf, Array.prototype.some, Array.isArray, Array.prototype.filter,  Array.prototype.map and Function.prototype.bind.
I write a demo use `<script src="https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver"></script>` for ie8 is still not working.

**Comment by JakeChampion** [comment]
@santinoDu This will make it work in IE8 -- `<script src="https://polyfill.io/v2/polyfill.min.js?features=default,IntersectionObserver"></script>`

**Comment by santinoDu** [comment]
@JakeChampion I have tried `<script src="https://polyfill.io/v2/polyfill.min.js?features=default,IntersectionObserver"></script>`, failed again in IE8. 

It seems that `jsfiddle.net` is not friendly with IE8, I copy the response of https://polyfill.io/v2/polyfill.min.js?features=default,IntersectionObserver to local .
The error in IE8's console: Object not support this method, `Object.defineProperty`

I test the demo locally.
Here is my test: [http://jsfiddle.net/b4yo8z3n/2](url)

**Comment by miketaylr** [comment]
I don't think we intend to support IE7 or IE8 (which are hopefully long behind us). But thanks for the report.

**Comment by santinoDu** [comment]
Can't agree more! We don't need to support IE8 anymore.
