### ISSUE TITLE
opacity and transition 

### ISSUE THREAD

**Issue by krom-xr** [w3c/IntersectionObserver#322]
I have a css code

```
    div.class-name {
      width: 100%;
      opacity: 0;
      transition: opacity 3s ease-in;
    }

    div.class-name.no-opacity {
      span { opacity: 1; }
    }

```

element placed on page - and have no intersection with webview

but when i add element to observer - it triggered twice

first - entry.isIntersecting === true, entry.intersectionRatio === 0
and 
second (about 3 second)  - entry.isIntersecting === false, entry.intersectionRatio === 0

```
  const observer = new IntersectionObserver((entries)=> {
    const entry = entries[0];
    const target = entry.target;
    console.log('intersection? - ', entry.isIntersecting, entry.intersectionRatio)
  }, {});


//at this moment element have no intersection with webview 
const div = document.querySelector('div.class-name'); 
div.classList.add('no-opacity');
observer.observe(div);

```
Browser - Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS - Mac Os High Sierra 10.13.6

**Comment by cWillow** [comment]
This a couple of months old but I have the same issue. Can I check if it's on the radar, or are there any suggestions for a workaround?

**Comment by benjvmin** [comment]
Here is a reference the Chromium bug, it's current status is fixed and will get released with Chrome 72 I believe

https://bugs.chromium.org/p/chromium/issues/detail?id=910741#c13

**Comment by krom-xr** [comment]
quite well

**Comment by bogas04** [comment]
This is odd. So [we use](https://www.swiggy.com/bangalore/restaurants) IntersectionObserver to lazy load images, however we use an effect of animating opacity. The above fix actually breaks it now as the image is intersecting, but has opacity of 0.

What's the take on this? Does intersection also mean visibility? What if we want to increase opacity gradually as the element comes into view?
