### ISSUE TITLE
Add check for `window` and fallback to `global` for node support

### ISSUE THREAD

**Issue by wescravens** [w3c/IntersectionObserver#327]
Is there any reason we couldn't add a definition check for `window` and fallback to `global` if it's undefined, so that the polyfill can at least be imported into a server rendered React app without causing any errors.  I know I could just define a window object on the node side, but no other libraries or polyfills that we use require my team to do so.

**Comment by JakeChampion** [comment]
What is the need for running the polyfill code within a non-browser environment?

**Comment by wescravens** [comment]
None of the API needs to be used server-side, but I need to be able to at least import the polyfill without an error being thrown since my React components are server and client rendered.

**Comment by wescravens** [comment]
I'm going to close this as I think I can just swap with an empty module with Babel.

**Comment by philipwalton** [comment]
My opinion is it doesn't make sense for every client side library to be node friendly just so it can run in React SRR scenarios. A much better solution is for SSR tools to minimally stub the browser environment so they can work without error.

Furthermore, if every client-side library injects a bunch of boilerplate code to detect node, all that code has to get downloaded by every user, which is unnecessary and wastes people's data.
