### ISSUE TITLE
What is the meaning of isIntersecting?

### ISSUE THREAD

**Issue by anticitizen4** [w3c/IntersectionObserver#328]
> True if the target intersects with the root; false otherwise. This flag makes it possible to distinguish between an IntersectionObserverEntry signalling the transition from intersecting to not-intersecting; and an IntersectionObserverEntry signalling a transition from not-intersecting to intersecting with a zero-area intersection rect (as will happen with edge-adjacent intersections, or when the boundingClientRect has zero area).

Is it meant to distinguish in which direction the root is moving? Or is it just a shortcut for `intersectionRatio !== 0`?

This fiddle https://jsfiddle.net/wuka38z1/ shows different behaviors for Firefox and Chrome.

**Comment by mpb** [comment]
intersectionRatio !== 0 doesn't work super well with zero-area elements, so isIntersecting is meant to disambiguate that situation.

**Comment by OZZlE** [comment]
but can `change.intersectionRatio` ever be `>0` if the element is in view but 0 height and 0 width?

**Comment by ccjmne** [comment]
@OZZlE Probably not.  
However, consider the case where that zero-by-zero element is **over** an area of interest.
Their `intersectionRatio` is `0`, but (IIRC), `isIntersecting` would then be `true`.

**Comment by OZZlE** [comment]
@ccjmne thanks for clearing it up! :-)
