### ISSUE TITLE
Broken links in explainer.md

### ISSUE THREAD

**Issue by chinskiy** [w3c/IntersectionObserver#329]
Greetings!
Links at [this](https://github.com/w3c/IntersectionObserver/blob/b4bfbbc8e8a62b7e0ad3e4b182b3e35d7eb46afd/explainer.md#observing-position) section of `explainer.md` are broken. 
First link redirects me on main page and second shows `This site can’t be reached`

**Comment by miketaylr** [comment]
The link seems fixed now, thanks for the report.
