### ISSUE TITLE
Clarify validity of empty string rootBounds

### ISSUE THREAD

**Issue by alijuma** [w3c/IntersectionObserver#330]
Chrome treats an empty string value of rootBounds as valid, interpreted as 0px in all directions. I've matched this behavior in WebKit. This behavior seems reasonable, but the [spec text](https://w3c.github.io/IntersectionObserver/#parse-a-root-margin) says that a parsed string with 0 tokens is invalid.

**Comment by miketaylr** [comment]
The spec currently says "[If there are zero elements in tokens, set tokens to ["0px"].](https://www.w3.org/TR/intersection-observer/#intersectionobserver-implicit-root:~:text=If%20there%20are%20zero%20elements%20in%20tokens%2C%20set%20tokens%20to%20%5B%220px%22%5D.)", so I think this was addressed. Please let me know if I'm misunderstanding, thanks!
