### ISSUE TITLE
Should be "thresholdIndex" and not "threshold" in "Assign threshold to intersectionObserverRegistration’s previousThresholdIndex property."

### ISSUE THREAD

**Issue by amn** [w3c/IntersectionObserver#332]
It seems to me that the correct wording of the sentence should be instead:

"Assign *thresholdIndex* to intersectionObserverRegistration’s previousThresholdIndex property."

There is no *threshold* definition in the list of steps for the algorithm outlined in section 3.2.5, and assigning a threshold to a variable that by all accounts is designed to store a threshold index, further points to an omission or a simple spelling error here.

**Comment by miketaylr** [comment]
It seems like this was fixed, the current language states, "Assign thresholdIndex to intersectionObserverRegistration’s previousThresholdIndex property." (in https://w3c.github.io/IntersectionObserver/#update-intersection-observations-algo).

Thanks for the issue.
