### ISSUE TITLE
IE11 with Generated iFrame Fails to Fire

### ISSUE THREAD

**Issue by Kikketer** [w3c/IntersectionObserver#337]
Edit: This also fails in Safari
I realize this is kind of an edge case but it's something I need to figure out for my project.  The use case is as follows:
The parent page generates an iFrame.  That iFrame gets elements appended to it and within that we have items that need to be observed.

In IE11 it seems that it's unable to use the `root` properly when it's set to any of the following:
 - The iframe contentDocument.documentElement
 - The body element of the inner iframe
 - The `inner-box` that's created within the iframe

Here's just a snippet of code where we set the options to be any one of the 3 above items.
```
        // Setup the observer
        // Can root any: documentElement, body, or innerBox (all work in Chrome)
        var options = {
          root: doc.documentElement,
          //root: innerBox,
          // root: bod,
          rootMargin: '0px',
          threshold: 1.0
        }
        var callback = function(entries, observer) {
          entries.forEach(function(entry) {
            result.innerHTML = 'Observed: ' + entry.intersectionRatio
          })
        }
        var observer = new IntersectionObserver(callback, options)
        var reSelectedObs = doc.getElementById('observe-me')
        reSelectedObs.style.background = 'orange'
        observer.observe(reSelectedObs)
```

The full code can be found here: https://github.com/Kikketer/ieframe-observe/blob/w3c-polyfill/index.html

And it can be viewed (use an IE vm if need be): http://htmlpreview.github.io/?https://raw.githubusercontent.com/Kikketer/ieframe-observe/w3c-polyfill/index.html

**Comment by philipwalton** [comment]
Sorry for the slow reply. The `IntersectionObserver` polyfill does not support iframes at all. I've added a [limitations section](https://github.com/w3c/IntersectionObserver/tree/master/polyfill#limitations) to the docs explaining that fact (and why). Sorry for any confusion not clearly stating this before may have caused.
