### ISSUE TITLE
"schedule an iteration of the event loop"

### ISSUE THREAD

**Issue by jakearchibald** [w3c/IntersectionObserver#343]
http://w3c.github.io/IntersectionObserver/v2/#dom-intersectionobserver-observe step 5

> Schedule an iteration of the event loop in the root's browsing context.

Iterations in the event loop don't need scheduling, so it isn't clear what the intent is here.

**Comment by szager-chromium** [comment]
I think this is better expressed by a change to the HTML processing model [spec](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model), in section 10.3, as follows (**bold text** is new):

3. _Unnecessary rendering_: If there are browsing contexts browsingContexts for which the user agent believes updating the rendering would have no visible effect and which possess no Document objects with a non-empty map of animation frame callbacks, **nor any Elements that are the root of an IntersectionObserver that requires updating**, then remove from docs all Document objects whose browsing context is in browsingContexts. Invoke the mark paint timing algorithm for each Document object removed.

WDYT?

**Comment by szager-chromium** [comment]
After this:

https://github.com/w3c/IntersectionObserver/pull/445

The "schedule an iteration" language is no longer necessary and can be removed.
