### ISSUE TITLE
Should isIntersecting be depended on the threshold value?

### ISSUE THREAD

**Issue by alisaitbilgi** [w3c/IntersectionObserver#345]
**isIntersecting** value (as [spec](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserverentry-isintersecting) says) is false in two conditions. **Target** has no intersections with the **root** or when the **boundingClientRect** has zero area. However, I've realized that on Chrome the value of **isIntersecting** is depending on the threshold value. On the other hand Firefox doesn't make the **isIntersecting** value false when **target** gets lost the intersection with the **root**.  Polyfill has the same implementation as the spec says. And on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Thresholds) the explanation is: "If isIntersecting is true, the target element has become at least as visible as the threshold that was passed. If it's false, the target is no longer as visible as the given threshold."

So, which one must be selected? I think it is also related with #328 

Chrome version: 72.0.3626.96 (Official Build) (64-bit)
Firefox version: 65.0 (64 bit)

**Comment by szager-chromium** [comment]
When boundingClientRect has zero area, the following states are possible:

If target is intersecting:
  isIntersecting=true
  intersectionRatio=1

If target is not intersecting:
  isIntersecting=false
  intersectionRatio=0

That's true no matter what the threshold values are.

**Comment by szager-chromium** [comment]
This is discussed in some detail in #432, especially:

https://github.com/w3c/IntersectionObserver/issues/432#issuecomment-686702820

I'm closing this issue, further discussion should happen on #432.
