### ISSUE TITLE
Polyfill not working on iOS DOM change display:none -> display:block

### ISSUE THREAD

**Issue by GameKyuubi** [w3c/IntersectionObserver#347]
When using code like [this](https://codepen.io/GameKyuubi/pen/daJgGZ), `IntersectionObserver` will not report the change from `display:none` to `display:block` on iOS.  In my case I am using `lozad.js` on both image elements.  The thumbnail is loaded properly using lozad.js, but when clicked the lightbox is not.  Upon scrolling a bit, the change is detected and the image is loaded.  The workaround is to set a polling interval as specified [here](https://github.com/w3c/IntersectionObserver/tree/master/polyfill), but optimally this shouldn't be necessary as the documentation says changes in the DOM are supposed to be detected.

**Comment by sudhirj** [comment]
Have you already tried setting the POLL_INTERVAL as documented in  https://github.com/w3c/IntersectionObserver/tree/master/polyfill#configuring-the-polyfill 

`display` property changes aren't efficiently discoverable in the polyfill, so you'll need to turn on the polling manually.

**Comment by philipwalton** [comment]
Is this on Safari or iOS WebView? I've heard several reports of bugs on iOS WebView, and I wouldn't be surprised if this isn't one of them.

Also, can you check to see if this is a problem on the latest iOS (which should support `IntersectionObserver` natively now)?

**Comment by zavr-1** [comment]
Yeah I've noticed this issue as well! The images don't come up when their parent element becomes visible on iOS with the polyfill.

**Comment by miketaylr** [comment]
> Is this on Safari or iOS WebView? I've heard several reports of bugs on iOS WebView, and I wouldn't be surprised if this isn't one of them.
> 
> Also, can you check to see if this is a problem on the latest iOS (which should support `IntersectionObserver` natively now)?

Given the lack of activity here, let's close as incomplete.

If others are running into this issue w/ the native implementation provided by iOS (webview or Safari), I would recommend filing a bug against https://bugs.webkit.org/
