### ISSUE TITLE
license field is invalid SPDX

### ISSUE THREAD

**Issue by ljharb** [w3c/IntersectionObserver#348]
https://github.com/w3c/IntersectionObserver/blob/master/polyfill/package.json#L19 is an invalid SPDX identifier. Can that be fixed?

**Comment by JakeChampion** [comment]
It looks correct according to https://spdx.org/licenses/W3C-20150513.html

**Comment by ljharb** [comment]
hmm - npmjs.com/licensee complains. @kemitchell?

**Comment by kemitchell** [comment]
Valid identifier.

**Comment by ljharb** [comment]
Thanks, I’ll file an issue on licensee then :-)
