### ISSUE TITLE
Observer/Polyfill not working in Instagram in-app browser on iOS

### ISSUE THREAD

**Issue by neefrehman** [w3c/IntersectionObserver#349]
I'm working on two projects where the polyfill isn't working on Instagram's in-app browser on iOS (the only browser I've had any issues with). I've using IntersectionObserver to make a [Vanilla lazy-loader](https://github.com/neefrehman/lzy) which is how I came across the issue.

An example: on my personal site ([neef.co/photos](https://neef.co/photos)) when accessed through Instagram iOS the lazy-loader isn't working so all image areas are coming up blank

To get around this I've added a userAgent check by following [this blog post](https://supergeekery.com/blog/detecting-the-instagram-in-app-browser), and directly loading the images without the Observer if Instagram is the browser.

```javascript
if (isInstagram) {
    images.forEach(image => image.setAttribute("src", image.getAttribute("data-src")));
} else {
    // Do regular loading with IntersectionObserver
}
```

I'm not sure exactly where the issue lies but it would be great to fix this bug to get the PolyFill working across all browsers.

**Comment by neefrehman** [comment]
Just discovered the polyfill also doesn't work on the Google iOS app browser, so have adapted by code to the following, successfully:

```javascript
if (!window.IntersectionObserver) {
    images.forEach(image => image.setAttribute("src", image.getAttribute("data-src")));
} else {
    // Do regular loading with IntersectionObserver
}
```

**Comment by netmet12** [comment]
I'm also having issues with ios browsers,  it's not respecting unobserve or disconnect methods

**Comment by philipwalton** [comment]
It sounds to me like this may be a bug with iOS WebView. Do you still see the problem on the latest iOS?

(BTW, Safari and iOS WebView should support IntersectionObserver natively now.)

**Comment by neefrehman** [comment]
I think you're right about the bug with WebView. The new version of iOS is working across all browsers I've tested on the device!
