### ISSUE TITLE
Initial display doesn't respect threshold value.

### ISSUE THREAD

**Issue by jchnxu** [w3c/IntersectionObserver#357]
https://github.com/w3c/IntersectionObserver/blob/b38e62ba74253840800159c4d224dc2f287e1025/polyfill/intersection-observer.js#L334-L350

@philipwalton Hi, Phillip! As I've found during my development process. When an entry is moved in or out of root element, the code doesn't run `_hasCrossedThreshold `. Is this behavior expected?

The MDN docs doesn't specify the behavior on show/hide, it just says when crossing the threshold the callback should be triggered. https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Intersection_change_callbacks

I tested on my Chrome 73 OSX, show/hide respects threshold value. However the native implementation of an android 4.4.4 native browser at hand behave just like your code does.

If this is the wrong behavior, I'd like to submit a pull request. And please let me know if this is intended.

**Comment by miketaylr** [comment]
> However the native implementation of an android 4.4.4 native browser at hand behave just like your code does.

@jchnxu Some three years later, do more modern version of Android browser (Chrome?) still have this bug?

**Comment by jchnxu** [comment]
> > However the native implementation of an android 4.4.4 native browser at hand behave just like your code does.
> 
> @jchnxu Some three years later, do more modern version of Android browser (Chrome?) still have this bug?

However I don't have that phone anymore. I don't know so I guess you don't need to care about it.

**Comment by miketaylr** [comment]
All good, thanks for the response.
