### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by matt3224** [w3c/IntersectionObserver#359]
I can't see changelog and theres nothing in releases, are the differences between version noted anywhere?

**Comment by LukoyanovE** [comment]
And/or tags for releases

**Comment by szager-chromium** [comment]
This spec is not yet a CR, so it is pretty much a live document without versioning or releases. The only changelog is the git commit history.

**Comment by lencioni** [comment]
@szager-chromium it would be helpful to have a changelog for the [polyfill npm package](https://github.com/w3c/IntersectionObserver/tree/master/polyfill), which just published version 0.11.0, that categories the changes by things like breaking change, new feature, bugfix, etc. This would help folks know what to look out for when updating.

**Comment by jonathantneal** [comment]
While it’s not as good as a proper CHANGELOG.md, here is a list of commits between v0.10.0 and v0.11.0.

https://github.com/w3c/IntersectionObserver/compare/1e93620...c2c61b7
