### ISSUE TITLE
Click on scrollbar doesn't trigger intersection callback

### ISSUE THREAD

**Issue by Aetet** [w3c/IntersectionObserver#377]
Click on scrollbar doesn't trigger intersection callback.
Example:

If we have long grid with 50 items. 

Client window contains only 20 items. 

We observe 25th element.

http://kb.mozillazine.org/Ui.scrollToClick must be true - 1

If we click at 49th element area - there's no triggerred event for intersection for 25th element.

Is there any workaround for this behaviour? It seems like blocker for implementing lazy load rendering.

**Comment by szager-chromium** [comment]
If this is a bug in a particular browser's implementation, please file a bug in the issue tracker for that browsers.

**Comment by Aetet** [comment]
@szager-chromium this behaviour doesn't cover in any spec. So what is reference for it?

**Comment by szager-chromium** [comment]
It would be helpful if you could construct a simple test page that demonstrates the problem.
