### ISSUE TITLE
Not working on Firefox?

### ISSUE THREAD

**Issue by felixwestphal** [w3c/IntersectionObserver#379]
In our angular project we're trying to use the intersection observer to replace divs that are not visible with empty divs with the same height.

This is working on Chrome and Safari, but on Firefox it's not. The intersection rectangle width is always zero.

The parent div of the content that is being observed doesn't have any css properties set - could this be an issue for the calculation? How is this working then on Chrome and Safari? What properties would need to be set for this to work?

<div>
  <ng-content></ng-content>
</div>

**Comment by szager-chromium** [comment]
This should be filed a Firefox bug:

https://bugzilla.mozilla.org/
