### ISSUE TITLE
WebApps WG agenda for TPAC 2019 (Fukuoka, September 19-20)

### ISSUE THREAD

**Issue by szager-chromium** [w3c/IntersectionObserver#380]
Intersection with iframe's scrolling viewport:
https://github.com/w3c/IntersectionObserver/issues/372

Clear queued entries on unobserve/disconnect:
https://github.com/w3c/IntersectionObserver/issues/356

IntersectionObserver V2 proposal:
https://github.com/w3c/IntersectionObserver/issues/295

layout viewport vs. visual viewport:
https://github.com/w3c/IntersectionObserver/issues/266

**Comment by marcoscaceres** [comment]
See also https://github.com/w3c/IntersectionObserver/issues/381 

Would  be great to have some follow up there...
