### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/IntersectionObserver#381]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by marcoscaceres** [comment]
@szager-chromium, looking forward to the  update at TPAC... if you can provide any details beforehand  that would be greatly appreciated.

**Comment by szager-chromium** [comment]
Sorry for the delay...

I am scrambling a bit to finish some edits to the spec for settled issues, but that's just mechanical stuff, nothing that requires deliberation. Aside from the V2 proposal, the spec has been very stable for the past 12 months.

Aside from that, I believe the spec to be ready for CR, and I hope to make it official at TPAC. Beyond that, there are a few issues in the tracker which I have marked for discussion at TPAC, including the V2 proposal (which has shipped in chromium):

https://github.com/w3c/IntersectionObserver/issues/380

**Comment by zcorpan** [comment]
I'd like to discuss these topics, in relation to lazy-loading in HTML:

- Allow dynamically changing rootMargin https://github.com/w3c/IntersectionObserver/issues/428
- Ability to have automatic rootMargin for all nested scroll containers  https://github.com/w3c/IntersectionObserver/issues/431

**Comment by zcorpan** [comment]
Sorry, wrong issue. Maybe this should be closed? Moving to #435

**Comment by miketaylr** [comment]
AFAICT, 2019 already happened. So let's close here.
