### ISSUE TITLE
rootMargin: the order of value description is confusing :(

### ISSUE THREAD

**Issue by nake226** [w3c/IntersectionObserver#383]
Isn't it confusing??
The order should be as same as the one of margin(css).
---
### css
> margin: top, right, bottom, left

### rootMargin
> rootMargin: bottom, left, top, right

If I'm wrong, please forget it 🤣

**Comment by szager-chromium** [comment]
You're wrong; from the spec:

"the four values indicating the amount the top, right, bottom, and left edges, respectively, are offset..."

**Comment by nake226** [comment]
thx
