### ISSUE TITLE
Complete i18n self-review

### ISSUE THREAD

**Issue by LJWatson** [w3c/IntersectionObserver#397]
Please could the editor(s) complete a self-review for i18n, using the [short review checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist), to assist the I18n WG in their horizontal review (w3c/i18n-activity#793)

**Comment by xfq** [comment]
Note that there is an open issue with the `i18n-needs-resolution` label (documented [here](https://w3c.github.io/documentreview/#working_with_horizontal_review_labels)): https://github.com/w3c/IntersectionObserver/issues/259
