### ISSUE TITLE
PING Review: No privacy considerations section

### ISSUE THREAD

**Issue by brentzundel** [w3c/IntersectionObserver#403]
I reviewed this specification on behalf of the PING.
The specification lacks a privacy considerations section. The designers of the specification are in a unique position to contemplate the privacy implications of the technology they are designing, and a section that outlines these privacy considerations should be included.
This specification increases the ability of websites to efficiently track user activity. Recommended and required mitigations so that user privacy is not compromised should be included as part of the privacy considerations section.

**Comment by szager-chromium** [comment]
@brentzundel Please take a look:

https://github.com/w3c/IntersectionObserver/pull/458

**Comment by brentzundel** [comment]
Looks good to me, thank you.
