### ISSUE TITLE
Flex Order 

### ISSUE THREAD

**Issue by innerop** [w3c/IntersectionObserver#410]
How does IntersectionObserver behave with respect to the visual order for Flex elements (specified in CSS by 'order') ?  Will it register an intersection if Flex order of an element changes such that it is visually intersecting? Just curious / have not had time to test it. Thanks.

**Comment by szager-chromium** [comment]
IntersectionObserver is completely based on physical layout, so if you make any style change to an element (like changing flex-order) that affects the element's layout, it will be detected by IntersectionObserver.
