### ISSUE TITLE
import 'intersection-observer' not work

### ISSUE THREAD

**Issue by stoneshower** [w3c/IntersectionObserver#413]
Is it possible to use `import` in a JS file to use this polyfill?

```
import 'intersection-observer'
```

Or do I need to add below in my webpack.config.js?
```
require('intersection-observer')
```

**Comment by impeiran** [comment]
using `import 'intersection-observer'` in a JS file powered by webpack is fine :)

**Comment by stoneshower** [comment]
Thank you! It works. I wanted to confirm so now I feel I'm on the right track :)
