### ISSUE TITLE
prop "is visible" doesn't work in some cases.

### ISSUE THREAD

**Issue by OlegBrony** [w3c/IntersectionObserver#417]
I have a div wrapper with fixed width and second div with bigger width. In inner div I have some elements that I want to observe, but the 'isVisible' prop is always false. [sandbox](https://codesandbox.io/s/hopeful-poitras-402kf)

**Comment by szager-chromium** [comment]
The 'isVisible' property is currently only implemented in chromium, and it needs to be activated when constructing the IntersectionObserver; see:

https://w3c.github.io/IntersectionObserver/v2/#dom-intersectionobserverinit-trackvisibility

If you believe Chrome or Edge is not behaving correctly according to the specification, please file a bug in the chromium bug tracker (crbug.com).
