### ISSUE TITLE
How about we move the polyfill out? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IntersectionObserver#433]
It might be good to move the polyfill out... then it makes it easier for us to manage spec issues and polyfill issues.

**Comment by siusin** [comment]
We can create a new repo for the polyfill under w3c if needed. @philipwalton would you be willing to be the maintainer?

**Comment by szager-chromium** [comment]
I think it's also worth discussing whether we should just freeze/archive the polyfill code and auto-close the polyfill issues, now that IntersectionObserver is supported natively by all major browsers.

**Comment by siusin** [comment]
SGTM :)

**Comment by marcoscaceres** [comment]
@szager-chromium, can we take this up again? i.e., close/freeze all the polyfill stuff?

**Comment by miketaylr** [comment]
@marcoscaceres @szager-chromium I'm triaging all the issues currently - I think it makes sense to archive/freeze the polyfill once we go through them all. Some are valid (typo in code), but most appear to be old browser bugs that should be handled by native implementations now. My plan is to close those and we'll see where we're at (perhaps cut one last version).

**Comment by marcoscaceres** [comment]
Thanks for the update and helping with this, @miketaylr!

**Comment by miketaylr** [comment]
I had a chat with @emilio about this, and he agrees that we should just remove it from the repo. @philipwalton - any thoughts of where we should move this? Deleting it entirely without the ability to update npm for an emergency hotfix maybe isn't the best idea. But I'm not sure if anybody really wants to maintain this... maybe we move it to GoogleChromeLabs and archive it?

**Comment by philipwalton** [comment]
I'm fine with moving it to GoogleChromeLabs and archiving it. We can work with folks on our OSS team to get the repo created.
