### ISSUE TITLE
TPAC planning and specification status report

### ISSUE THREAD

**Issue by LJWatson** [w3c/IntersectionObserver#435]
TPAC will be virtual this year. W3C is finalising the details but it is likely there will be events for the whole W3C community during the week of 26 to 31 October (as originally planned), with WG able to organise their own meetings in/around that week.

There are two things we need you to do:
1. Let @marcoscaceres  and I know before 17 July if you want meeting time to talk about your specification.
2. Post a specification status report before 30 September.

The specification status report should include:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

Your specification status report from 2019 is at #381

**Comment by zcorpan** [comment]
I'd like to discuss these topics, in relation to lazy-loading in HTML:

Allow dynamically changing rootMargin #428
Ability to have automatic rootMargin for all nested scroll containers #431

**Comment by miketaylr** [comment]
I think this can be closed now.
