### ISSUE TITLE
Polyfill Release Notes/Changelog

### ISSUE THREAD

**Issue by mark-monteiro** [w3c/IntersectionObserver#439]
Can a changelog or release notes be added to the repository for updates to the polyfill package?

Opening this up as an issue as requested here: https://github.com/w3c/IntersectionObserver/pull/437#issuecomment-657729366

**Comment by szager-chromium** [comment]
Just FYI, you shouldn't expect much further development on the polyfill now that IntersectionObserver is supported natively by all major browsers.

**Comment by standy** [comment]
Please, add changelog or release notes. Updating package looks risky for now

**Comment by miketaylr** [comment]
This sounds like a reasonable request, if a new version is released.

**Comment by miketaylr** [comment]
The polyfill is being removed in https://github.com/w3c/IntersectionObserver/pull/499 (see #433 for discussion). 

If you can still reproduce bugs in the native implementations, filing bugs in the various bug tracks would be really helpful.

I'm going to close this as wontfix, but thanks for taking the time to report this issue!
