### ISSUE TITLE
rootRect without passed root parameter

### ISSUE THREAD

**Issue by ZachBird** [w3c/IntersectionObserver#440]
if not pass root parameter when create instance, dependence on [mdn document](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

> Defaults to the browser viewport if not specified or if null.

so, in 「_getRootRect」 function，if without 「this.root」, may the rootRect should be: 
```
 rootRect = {
      top: 0,
      left: 0,
      right: window.innerWidth,
      width: window.innerWidth,
      bottom: window.innerHeight,
      height: window.innerHeight
};
```

**Comment by szager-chromium** [comment]
innerWidth/innerHeight represent the browser window's layout viewport. Issue #26 discusses whether the implicit root should be the layout viewport or the [visual viewport](https://wicg.github.io/visual-viewport/), with the balance of opinion favoring the visual viewport. The IntersectionObserver spec needs to be updated, but I'm going to close this issue and attach any PR's to issue #26.
