### ISSUE TITLE
Looking for an additional spec Editor

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IntersectionObserver#442]
Hi Folks involved in this work! We are looking for an additional spec Editor for this spec. If anyone is interested, we've love to hear from you.

**Comment by zcorpan** [comment]
I'm interested, but would need sponsorship to take this on.

**Comment by marcoscaceres** [comment]
Oops, closed by accident. 

@zcorpan thanks for offering. We had @Emilio from Mozilla step up to become editor also. @zcorpan, understood about requiring sponsorship.

**Comment by marcoscaceres** [comment]
@zcorpan, let us know how you want to proceed here. It be great to have you onboard if possible.

**Comment by marcoscaceres** [comment]
@zcorpan, now that you are at Moz... would you again be interested?

**Comment by zcorpan** [comment]
No unfortunately, not a current priority for me.

**Comment by marcoscaceres** [comment]
Ok, no problem. Though I’d check. Closing.

**Comment by ccjmne** [comment]
Hey @marcoscaceres,
On the odd chance that this thread was closed for inactivity, I'd like to throw my hat into the ring!
I'm not affiliated with any instantaneously recognisable company and haven't published anything noteworthy, but I'd be interested in helping out here if there's still a need for some spec editor.

**Comment by marcoscaceres** [comment]
hi @ccjmne! thanks for offering. My suggestion would be you try to pick up a few issues. We usually want someone to have track record and on-going contributions before we consider adding them to the editorial team.

**Comment by ccjmne** [comment]
Haha, that makes perfect sense. Thanks!
