### ISSUE TITLE
bower install breaking

### ISSUE THREAD

**Issue by jay8t6** [w3c/IntersectionObserver#470]
Not using master branch is breaking bower install. Any reason why you are using main branch instead of master?

**Comment by miketaylr** [comment]
It's fairly common to use main these days (see https://github.com/github/renaming and https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/).

That said, it looks like bower is configurable as to what branch it cares about: https://bower.io/docs/api/. I recommend you file a bug against whoever is maintaining said bower package. AFAICT, it's not in this repo (I could be wrong, it's my first day working on this spec).
