### ISSUE TITLE
when element is false then move to the bottom of the list - not working in safari

### ISSUE THREAD

**Issue by nirsh5** [w3c/IntersectionObserver#472]
I try to create a loop scroll effect.  the function goes like this: every time a section is getting out of the frame than the element moves to the bottom of it's container (using insertBefore method). 

It works perfectly in chrome but not at all in safari. 
[here's a js fiddle](https://jsfiddle.net/90sw7dhf/)
Would appreciate any help! Thanks

**Comment by marcoscaceres** [comment]
Thanks @nirsh5. If you think there is a web compat issue (please check also in Firefox!), it might be best to also file a bug at http://bugs.webkit.org. That way, folks over on the WebKit Team can evaluate if something is buggy in their engine, and in Safari.

**Comment by miketaylr** [comment]
I filed https://bugs.webkit.org/show_bug.cgi?id=241493 - let's let the WebKit folks take a look.
