### ISSUE TITLE
Safari 10 read only error

### ISSUE THREAD

**Issue by odedimgn** [w3c/IntersectionObserver#473]
When running the polyfill on Safari 8-10 we are getting on this line:
`  this.isIntersecting = !!entry.intersectionRect;`

TypeError: Attempted to assign to readonly property.

Thanks

**Comment by graemeenglish** [comment]
This also causes problems on chrome 94 and edge 94 when forcing the polyfill for testing using
<script>
  delete window.IntersectionObserver;
  delete window.IntersectionObserverEntry;
</script>
