### ISSUE TITLE
Status report and planning for TPAC 2021

### ISSUE THREAD

**Issue by LJWatson** [w3c/IntersectionObserver#479]
[TPAC](https://www.w3.org/2021/10/TPAC/#schedule) will be virtual again this year. There will be a WebApps WG meeting at some point between 24 and 29 October.

There are two things we need you to do in the meantime:
1. Let @marcoscaceres  and I know before 17 September if you plan to hold a specification specific meeting (in addition to the general WebApps WG meeting)
2. Post a specification status report before 30 September

Your specification status report should include:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

CC @siusin

**Comment by marcoscaceres** [comment]
Closing as done...
