### ISSUE TITLE
Intersection Observer delay when i scroll very fast

### ISSUE THREAD

**Issue by Flourad** [w3c/IntersectionObserver#480]

**Comment by miketaylr** [comment]
I'm going to close this due to a lack of actionable information. @Flourad if you're seeing this on a particular browser, please file a bug against their tracker: https://crbug.com, https://bugs.webkit.org/, https://bugzilla.mozilla.org/, etc.

**Comment by Edge00** [comment]
I have to this problem too.

**Comment by synasapmob** [comment]
it seem solve there https://stackoverflow.com/questions/61951380/intersection-observer-fails-sometimes-when-i-scroll-fast
