### ISSUE TITLE
An problem on safari iOS 15.0.1&15.4 ！

### ISSUE THREAD

**Issue by jinyuanZhou-Leo** [w3c/IntersectionObserver#493]
I can use IntersectionObserver by enabling webkit experimental features (intersectionObserver and requestIdleCallback)
It's like a one-off function. After refreshing the webpage it has no effect.
However, the compatibility judgment in this Polyfill source code still indicates that the IntersectionObserver function is supported

I am not an English speaker. Forgive me if there are any grammatical issues with the above description.

**Comment by emilio** [comment]
This should be reported to https://bugs.webkit.org/. cc @smfr
