### ISSUE TITLE
Avoiding applying both scrollMargin and rootMargin

### ISSUE THREAD

**Issue by progers** [w3c/IntersectionObserver#519]
Consider a developer using intersection observer to implement lazy loading for an iframe. There does not seem to be a good migration path to integrate `scrollMargin` while supporting engines that do not yet support it. Applying both `scrollMargin` and `rootMargin` will cause the margin to be doubled (if the root is a scrollport) in engines that support `scrollMargin` ([spec](https://w3c.github.io/IntersectionObserver/#intersectionobserver-root-intersection-rectangle:~:text=To%20apply%20scroll%20margin%20to%20a%20scrollport)). It does not seem easy to feature-detect `scrollMargin`.

Should we change the spec to only apply `rootMargin`, if specified, rather than `scrollMargin` + `rootMargin`, when calculating the root intersection when the root is a scrollport?

**Comment by emilio** [comment]
> It does not seem easy to feature-detect scrollMargin.

@progers what is wrong with the usual way of feature-detecting dictionary members?

```js
function isScrollMarginSupported() {
  let supported = false;
  new IntersectionObserver(() => {}, { get scrollMargin() { supported = true; });
  return supported;
}
```

Seems to work just fine...

**Comment by progers** [comment]
Thanks @emilio ! I just wasn't aware that this was a common pattern for feature detection. Given that, I think we can close this bug.

**Comment by emilio** [comment]
Also even easier (and cheaper): `"scrollMargin" in IntersectionObserver.prototype` or so
