### ISSUE TITLE
Should scrollMargin be applied to display:hidden containers?

### ISSUE THREAD

**Issue by szager-chromium** [w3c/IntersectionObserver#521]
According to the [spec](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserver-scrollmargin), `scrollMargin` is applied only to `scrollPorts`, and `display:hidden` does not qualify as a [`scrollport`](https://drafts.csswg.org/css-overflow-3/#scrolling) because it doesn't "allow the user to scroll clipped parts of its scrollable overflow area into view". But many of the [scroll-margin WPT](https://github.com/web-platform-tests/wpt/tree/master/intersection-observer) use `overflow:hidden` with the expectation that `scrollMargin` will be applied.

**Comment by tcaptan-cr** [comment]
Scrollports should allow for script scrolling as well. The intent with scrollMargin was support both user and script scrolling.

**Comment by tcaptan-cr** [comment]
Resolved via [Clarify that scripts can also scroll a scroll container](https://github.com/w3c/csswg-drafts/pull/10048#issuecomment-2019073142)
