### ISSUE TITLE
CFC to move IntersectionObserver from the WebApps WG to the CSS WG

### ISSUE THREAD

**Issue by siusin** [w3c/IntersectionObserver#526]
During the WebApps WG TPAC 2024 meeting, there were discussions about transferring certain aspects of the IntersectionObserver work to the CSS WG. The CSS WG has agreed to adopt IntersectionObserver in their next chartering period. Therefore, this is a Call for Consensus to formally move the IntersectionObserver specification from the WebApps WG to the CSS WG.

For more details, please refer to the meeting minutes of both the WebApps WG and the CSS WG:
https://docs.google.com/document/d/1EtEFfQ3sJ6lECF3ojmbLKIH7iKN4RdGrapVosQB-wqI/
and
https://log.csswg.org/irc.w3.org/css/2024-09-26/#e1651268

The latest version of the spec is available at:
https://w3c.github.io/IntersectionObserver/

To show support for the decision, please add a 👍.

If you'd like to raise a Formal Objection to this decision, please do so by using a 👎 by 28 October, 2024.
Please include the rationale for your objection to its publication as a GitHub comment or email the working group.

If you have other comments, suggestions, or found bugs, we invite you to file an issue.

**Comment by LJWatson** [comment]
With multiple expressions of support and no objections, the proposal to move the Intersection Observer spec to the CSS WG passes.
