### ISSUE TITLE
Don't call public API methods; instead call their backing algorithms

### ISSUE THREAD

**Issue by domenic** [w3c/IntersectionObserver#55]
A few places in the spec refer to public API methods:

> The DOMRect corresponding to the target’s getBoundingClientRect().
> 
> Let boundingClientRect be the value of target.getBoundingClientRect(). 
> 
> For each observer in node’s internal [[RegisteredIntersectionObservers]] slot, invoke unobserve() on observer, passing in node as target. 

This is not quite the right thing to do, since it implies that e.g. if I do `Element.prototype.getBoundingClientRect = () => { throw new Error("boo"); }`, you'll call that overriden function.

Instead, the correct thing to do is to refer to the backing concept or algorithm behind that method. For unobserve, you'd probably define something in the processing model like

"To **remove an intersection observer** _o_ from an Element _target_, perform the following steps: ..."

Then unobserve() algorithm would do "Remove the intersection observer _this_ from _target_," and instead of doing "invoke unobserve()," you would do a similar thing.

For getBoundingClientRect(), things are more annoying, since CSSOM View hasn't factored themselves appropriately. There you could do something like "Let boundingClientRect be a DOMRectReadonly obtained by the same algorithm as that of Element's getBoundingClientRect() performed on target."

**Comment by mpb** [comment]
Fixed `unobserve()` in #67.

Not sure the best way to address `getBoundingClientRect()`.

**Comment by ojanvafai** [comment]
For getBoudningClientRect lets used Domenic's text and file a bug against cssom-view asking for a name for this algorithm so we can refer to it directly.

**Comment by mpb** [comment]
Added Dominic's text in #71.

**Comment by domfarolino** [comment]
> For getBoudningClientRect lets used Domenic's text and file a bug against cssom-view asking for a name for this algorithm so we can refer to it directly.

Has this been done?

**Comment by szager-chromium** [comment]
I filed a bug on cssom-view:

https://github.com/w3c/csswg-drafts/issues/5614

**Comment by annevk** [comment]
I'm reopening this as it's not fixed.

**Comment by miketaylr** [comment]
I sent in a PR to cssom-view, https://github.com/w3c/csswg-drafts/pull/7446
